application: hivepeek
version: 1
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: assets
  expiration: 30d

- url: /events/new
  login: admin
  script: _go_app

- url: /events/upload
  login: admin
  script: _go_app

- url: /events/calc
  login: admin
  script: _go_app

- url: /.*
  login: required
  script: _go_app
