application: hivepeek
version: 1
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: assets
  expiration: 30d

- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico

- url: /events/(new|upload|reset|calc)
  login: admin
  script: _go_app
  secure: always

- url: /.*
  login: required
  script: _go_app
  secure: always
